### ISSUE TITLE
illegal value null for text

### ISSUE THREAD

**Issue by KTAI-GIS** [claeis/av2geobau#1]
[AV_Appenzell_DM01_CH_LV95_test.zip](https://github.com/claeis/av2geobau/files/3341725/AV_Appenzell_DM01_CH_LV95_test.zip)
I made a short test with one of our AV ITF files. Got an error about an illegal null value. Test File from geodienste.ch  is attached.

**Comment by edigonzales** [comment]
Works for me with latest snapshot: http://jars.interlis.ch/ch/interlis/av2geobau/1.0.0-SNAPSHOT/av2geobau-1.0.0-20191015.122436-7-bindist.zip

Not sure but it reminds me of some errors I had too. I fixed them last year: https://github.com/claeis/av2geobau/commits/master

**Comment by KTAI-GIS** [comment]
Works for me with latest snapshot: http://jars.interlis.ch/ch/interlis/av2geobau/1.0.0-SNAPSHOT/av2geobau-1.0.0-20191015.122436-7-bindist.zip too!
I made some tests for the whole canton.

Great Job! Is there an official release soon?

**Comment by edigonzales** [comment]
I think there is a known issue with "half circles" which should be fixed in january. Then I guess it's ready for a release.

**Comment by claeis** [comment]
1.0.0 is done.

http://jars.interlis.ch/ch/interlis/av2geobau/1.0.0/av2geobau-1.0.0-bindist.zip
