### ISSUE TITLE
EO.Linienelemente, Radien

### ISSUE THREAD

**Issue by ghost** [claeis/av2geobau#4]
Evtl. werden bei den EO.Linienelementen die Kreisbögen nicht umgesetzt.

Komischerweise ist im Autocad die orange Linie vom Typ 3D-Linie. Wohingegen das EO.Flächenelement eine Polylinie ist.

Ist:
![image001](https://user-images.githubusercontent.com/24860761/81665441-0079f880-9441-11ea-9e7c-8cbf6120685f.png)

Soll:
![image002](https://user-images.githubusercontent.com/24860761/81665464-07087000-9441-11ea-8b10-48559ce9bd52.png)

EO.Linienelement ohne Kreisbogen:
![image003](https://user-images.githubusercontent.com/24860761/81665476-096aca00-9441-11ea-9673-a62a35d1dfae.png)

EO.Flaechenelement mit Kreisbogen, scheint i.O. zu sein:
![image004](https://user-images.githubusercontent.com/24860761/81665485-0bcd2400-9441-11ea-8ef7-d518983bd9b8.png)

**Comment by claeis** [comment]
ich habe den Code angeschaut, und sehe im Moment nichts (Also kein Unterschied zu POLYLINEs in anderen Tabellen (Bezirksgrenzabschnitt, Kantonsgrenzabschnitt, Landesgrenzabschnitt, Rohrleitungen)).

Ist es nur ein einzlner Kreisbogen, oder betrifft es alle (von POLYLINEs)?

**Comment by ghost** [comment]
Soweit ich feststellen kann, betrifft es Einzelobjekte.Linienelemente mit Radien, z.B. Bahngeleise.
![sshot-01](https://user-images.githubusercontent.com/24860761/83099148-d2392180-a0ac-11ea-81b2-a3f2de771097.png)
).

**Comment by claeis** [comment]
64a1d35188d747b0fffbf5be4ee899ea9911d32c
