### ISSUE TITLE
Dependency error

### ISSUE THREAD

**Issue by zigertiger** [claeis/av2geobau#5]
Unsere Entwickler melden:

"Wenn ich das JAR unter http://jars.interlis.ch/ch/interlis/av2geobau/1.0.1/av2geobau-1.0.1.jar brauche, dann erhalte ich einen Abhängigkeitsfehler."

"Die Version `1.0.2-er-Snapshot` hat bei mir auch einen Abhängigkeitsfehler. Die Version `1.0.0` geht aber."

**Comment by edigonzales** [comment]
Ich kanns mir nicht verkneifen: "Hallo, es geht nicht, bitte fixen".

Was machen deine Entwickler genau? Fehlermeldung? Welche Build-Software (?) verwenden sie? 

Testweise habe ich bei mir den gradle cache gelöscht und https://github.com/sogis/avdpool-camel mit Version 1.0.1 gebuildet. Scheint zu funktionieren.

**Comment by edigonzales** [comment]
Maven? Fehlermeldung irgendwas mit ili2c-tool-5.1.1?

**Comment by zigertiger** [comment]
OK, merci.
Ich weise sie mal an, selbst 1.0.1 zu builden.

Es wurde der JAR-Snapshot verwendet (versucht, zu verwenden).

**Comment by edigonzales** [comment]
Nein, sorry, nicht selbst builden. Ich meinte mit meinem Versuch, dass ich eine Software builden kann, die als Abhängigkeit av2geobau v1.0.1 verwendet.

**Comment by edigonzales** [comment]
http://jars.interlis.ch/ch/interlis/iox-ili/1.21.0/iox-ili-1.21.0.pom

Ich glaube Maven versteht die "+"-Syntax nicht.

**Comment by edigonzales** [comment]
Kann glaub geschlossen werden. Nach bilateralem Austausch mit dem Entwickler:

- Builden des Masters benötigt rst2html. War nicht vorhanden. Mit "-x usrdoc" schaltet man diesen Gradle-Task aus.
- Releases (binary distribution) sind auf jars.interlis.ch released.
