### ISSUE TITLE
add new parameter to filter conversion by Polygon

### ISSUE THREAD

**Issue by claeis** [claeis/av2geobau#7]
simple WKT (no arcs)

**Comment by kglaus** [comment]
@claeis 

Darf ich dich bitten, dieses Feature umzusetzen.

**Comment by kglaus** [comment]
@claeis 

Vielen Dank fürs umsetzen Claude.

Beim testen ist uns noch folgendes aufgefallen:

1. Die Liegenschaftsnummer kommen trotz `--perimeter` immer für das ganze itf mit. Ich denke das sollte nicht so sein.
![image](https://user-images.githubusercontent.com/71133987/216021360-1ee784ca-ab42-4be8-9284-f1d4d6b7d930.png)
3. Könntest du anstelle von `containts` `intersects` verwenden, damit alle Geometiren die den `--perimeter` berühren oder schneiden mitkommen und nicht nur die die komplett im `--perimeter` sind.

Könntest du bitte diese beide Punkte noch fixen/anpassen?
